services:
 web-tier:
  image: nginx
  container_name: web-tier
  ports:
   - 80:80
  volumes:
   - ./web:/usr/share/nginx/html
   - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
  depends_on: 
   - app-tier
  networks:
   - web-network
  
   
 

 app-tier: 
  build:
    context: ./app
  container_name: app-tier
  volumes:
   - ./app:/var/www/html
  depends_on:
   - db
  networks:
   - web-network
   - app-network


 db:
  image: mysql:5.7
  container_name: db-tier
  environment:
     MYSQL_ROOT_PASSWORD: pass1234
     MYSQL_DATABASE: registration_db
     MYSQL_USER: root
 
  ports: 
   - 3306:3306 
  volumes:
   - ./db:/var/lib/mysql
   - ./db-data/init.sql:/docker-entrypoint-initdb.d/init.sql
  networks:
   - app-network


volumes:
  db:

networks:
  web-network: 
  app-network:
