services:
 web:
  build:
    context: ./web
  ports:
   - 80:80
  volumes:
   - ./web:/usr/share/nginx/html
   - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
   
  networks:
   - app-net  
  depends_on:
   - app


 app:
  build:
     context: ./app
  volumes:
   - ./app:/usr/share/nginx/html
  environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  ports:
   - 3000:3000
  networks:
   - db-net
   - app-net
  depends_on:
   - db 

 db:
  image: mysql
  ports:
   - 3306:3306
  environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  volumes:
   - ./db:/var/lib/mysql
   - ./db-data/init.sql:/docker-entrypoint-initdb.d/init.sql
  networks:
   - db-net 


volumes:
  db:
  
networks:
  app-net:
  db-net:
